######################################################################
# Automatically generated by qmake (3.0) ?? ?? 21 22:27:17 2013
######################################################################

TEMPLATE = app
TARGET = NeuralNetwork
INCLUDEPATH += .

# Input
HEADERS += neuralnetwork.h \
    xmlreader.h
SOURCES += main.cpp \
           neuralnetwork.cpp \
    xmlreader.cpp
